### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [sergiormpereira/brain_tumor_grading#1]
Dear authors: 
    Recently I  have looking your this project and feel interested in it !could have a dataset of this project?   Thanks a lot! I am looking forward to your reply Sincerely!

Best regards.

**Comment by sergiormpereira** [comment]
Hello! Thank you for your interest in our work!

I do not own the dataset, but I used BRATS 2017's data. The webpage is [here](https://www.med.upenn.edu/sbia/brats2017/data.html). I can recommend checking it out to see if it is still available, or reaching out the organizers.

Once you acquire the data, you can get the (training, validation, test) splits using the IDs share [here](https://github.com/sergiormpereira/brain_tumor_grading/blob/master/brats2017_subjects_sets.py).

Hope this helps!

**Comment by yaolp123** [comment]
I am pleased to hear from your letter. Thank you very much.
